workflows:
  unity-ios:
    name: Unity iOS Build
    environment:
      vars:
        UNITY_VERSION: "2020.3.25f1"
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
    triggering:
      events:
        - push
    scripts:
      - name: Set up Unity
        script: |
          echo "Installing Unity Hub..."
          curl -O https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg
          hdiutil attach UnityHubSetup.dmg
          sudo cp -R "/Volumes/Unity Hub/Unity Hub.app" /Applications
          hdiutil detach "/Volumes/Unity Hub"
          echo "Installing Unity ${UNITY_VERSION} with iOS Build Support..."
          /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install --version ${UNITY_VERSION} --module ios
      - name: Build Xcode project
        script: |
          echo "Building Xcode project..."
          cd $CM_BUILD_DIR  # Navigate to the root directory where Unity-iPhone.xcodeproj is located
          xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/output/Unity-iPhone.xcarchive
      - name: Export IPA
        script: |
          echo "Exporting IPA..."
          xcodebuild -exportArchive -archivePath $HOME/output/Unity-iPhone.xcarchive -exportPath $HOME/output -exportOptionsPlist $CM_BUILD_DIR/exportOptions.plist
    artifacts:
      - $HOME/output/*.ipa
